version: "3"

services:
  django-web:
    container_name: django-web
    build: ./django
    command: python /code/mysite/manage.py runserver 0.0.0.0:80
    expose:
      - 80
    volumes:
      - ./django/code:/code
    depends_on:
      - django-db
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.entrypoints=web
      - traefik.http.routers.django.rule=Host(`django.localhost`)

  django-db:
    container_name: django-db
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web

networks:
  web:
    name: docker-mgr_web
    external: true
